// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: property_service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request and Response messages for the Create operation.
type CreatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      []string               `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID       string                 `protobuf:"bytes,3,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	AvailableDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=available_date,json=availableDate,proto3" json:"available_date,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	SaleType      uint32                 `protobuf:"varint,8,opt,name=sale_type,json=saleType,proto3" json:"sale_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyRequest) Reset() {
	*x = CreatePropertyRequest{}
	mi := &file_property_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyRequest) ProtoMessage() {}

func (x *CreatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyRequest.ProtoReflect.Descriptor instead.
func (*CreatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePropertyRequest) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *CreatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePropertyRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *CreatePropertyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePropertyRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CreatePropertyRequest) GetAvailableDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableDate
	}
	return nil
}

func (x *CreatePropertyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreatePropertyRequest) GetSaleType() uint32 {
	if x != nil {
		return x.SaleType
	}
	return 0
}

type CreatePropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyResponse) Reset() {
	*x = CreatePropertyResponse{}
	mi := &file_property_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyResponse) ProtoMessage() {}

func (x *CreatePropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyResponse.ProtoReflect.Descriptor instead.
func (*CreatePropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePropertyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request and Response messages for the Read operation.
type ReadPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPropertyRequest) Reset() {
	*x = ReadPropertyRequest{}
	mi := &file_property_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPropertyRequest) ProtoMessage() {}

func (x *ReadPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPropertyRequest.ProtoReflect.Descriptor instead.
func (*ReadPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadPropertyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadPropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      []string               `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID       string                 `protobuf:"bytes,4,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Available     *wrapperspb.BoolValue  `protobuf:"bytes,6,opt,name=available,proto3" json:"available,omitempty"`
	AvailableDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=available_date,json=availableDate,proto3" json:"available_date,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	SaleType      uint32                 `protobuf:"varint,9,opt,name=sale_type,json=saleType,proto3" json:"sale_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPropertyResponse) Reset() {
	*x = ReadPropertyResponse{}
	mi := &file_property_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPropertyResponse) ProtoMessage() {}

func (x *ReadPropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPropertyResponse.ProtoReflect.Descriptor instead.
func (*ReadPropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadPropertyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadPropertyResponse) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ReadPropertyResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReadPropertyResponse) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *ReadPropertyResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReadPropertyResponse) GetAvailable() *wrapperspb.BoolValue {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *ReadPropertyResponse) GetAvailableDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableDate
	}
	return nil
}

func (x *ReadPropertyResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReadPropertyResponse) GetSaleType() uint32 {
	if x != nil {
		return x.SaleType
	}
	return 0
}

// Request and Response messages for the Update operation.
type UpdatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Available     *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=available,proto3" json:"available,omitempty"`
	AvailableDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=available_date,json=availableDate,proto3" json:"available_date,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Category      []string               `protobuf:"bytes,6,rep,name=category,proto3" json:"category,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	SaleType      uint32                 `protobuf:"varint,8,opt,name=sale_type,json=saleType,proto3" json:"sale_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePropertyRequest) Reset() {
	*x = UpdatePropertyRequest{}
	mi := &file_property_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropertyRequest) ProtoMessage() {}

func (x *UpdatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropertyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePropertyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePropertyRequest) GetAvailable() *wrapperspb.BoolValue {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *UpdatePropertyRequest) GetAvailableDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableDate
	}
	return nil
}

func (x *UpdatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePropertyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePropertyRequest) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *UpdatePropertyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdatePropertyRequest) GetSaleType() uint32 {
	if x != nil {
		return x.SaleType
	}
	return 0
}

type UpdatePropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePropertyResponse) Reset() {
	*x = UpdatePropertyResponse{}
	mi := &file_property_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropertyResponse) ProtoMessage() {}

func (x *UpdatePropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropertyResponse.ProtoReflect.Descriptor instead.
func (*UpdatePropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePropertyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request and Response messages for the Delete operation.
type DeletePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePropertyRequest) Reset() {
	*x = DeletePropertyRequest{}
	mi := &file_property_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePropertyRequest) ProtoMessage() {}

func (x *DeletePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePropertyRequest.ProtoReflect.Descriptor instead.
func (*DeletePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePropertyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePropertyResponse) Reset() {
	*x = DeletePropertyResponse{}
	mi := &file_property_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePropertyResponse) ProtoMessage() {}

func (x *DeletePropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePropertyResponse.ProtoReflect.Descriptor instead.
func (*DeletePropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePropertyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_property_service_proto protoreflect.FileDescriptor

const file_property_service_proto_rawDesc = "" +
	"\n" +
	"\x16property_service.proto\x12\rmygrpcservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/api/annotations.proto\"\x9d\x02\n" +
	"\x15CreatePropertyRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x03(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aownerID\x18\x03 \x01(\tR\aownerID\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12A\n" +
	"\x0eavailable_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ravailableDate\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1b\n" +
	"\tsale_type\x18\b \x01(\rR\bsaleType\"(\n" +
	"\x16CreatePropertyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13ReadPropertyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc8\x02\n" +
	"\x14ReadPropertyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x03(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aownerID\x18\x04 \x01(\tR\aownerID\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x128\n" +
	"\tavailable\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\tavailable\x12A\n" +
	"\x0eavailable_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ravailableDate\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1b\n" +
	"\tsale_type\x18\t \x01(\rR\bsaleType\"\xaf\x02\n" +
	"\x15UpdatePropertyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\tavailable\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\tavailable\x12A\n" +
	"\x0eavailable_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ravailableDate\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x06 \x03(\tR\bcategory\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1b\n" +
	"\tsale_type\x18\b \x01(\rR\bsaleType\"(\n" +
	"\x16UpdatePropertyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15DeletePropertyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16DeletePropertyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xca\x06\n" +
	"\x0fPropertyService\x12U\n" +
	"\x06Create\x12$.mygrpcservice.CreatePropertyRequest\x1a%.mygrpcservice.CreatePropertyResponse\x12O\n" +
	"\x04Read\x12\".mygrpcservice.ReadPropertyRequest\x1a#.mygrpcservice.ReadPropertyResponse\x12U\n" +
	"\x06Update\x12$.mygrpcservice.UpdatePropertyRequest\x1a%.mygrpcservice.UpdatePropertyResponse\x12U\n" +
	"\x06Delete\x12$.mygrpcservice.DeletePropertyRequest\x1a%.mygrpcservice.DeletePropertyResponse\x12r\n" +
	"\fReadProperty\x12\".mygrpcservice.ReadPropertyRequest\x1a#.mygrpcservice.ReadPropertyResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/property/{id}\x12v\n" +
	"\x0eCreateProperty\x12$.mygrpcservice.CreatePropertyRequest\x1a%.mygrpcservice.CreatePropertyResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/property\x12{\n" +
	"\x0eUpdateProperty\x12$.mygrpcservice.UpdatePropertyRequest\x1a%.mygrpcservice.UpdatePropertyResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/v1/property/{id}\x12x\n" +
	"\x0eDeleteProperty\x12$.mygrpcservice.DeletePropertyRequest\x1a%.mygrpcservice.DeletePropertyResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/property/{id}B\"Z property-service/api/proto;protob\x06proto3"

var (
	file_property_service_proto_rawDescOnce sync.Once
	file_property_service_proto_rawDescData []byte
)

func file_property_service_proto_rawDescGZIP() []byte {
	file_property_service_proto_rawDescOnce.Do(func() {
		file_property_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_property_service_proto_rawDesc), len(file_property_service_proto_rawDesc)))
	})
	return file_property_service_proto_rawDescData
}

var file_property_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_property_service_proto_goTypes = []any{
	(*CreatePropertyRequest)(nil),  // 0: mygrpcservice.CreatePropertyRequest
	(*CreatePropertyResponse)(nil), // 1: mygrpcservice.CreatePropertyResponse
	(*ReadPropertyRequest)(nil),    // 2: mygrpcservice.ReadPropertyRequest
	(*ReadPropertyResponse)(nil),   // 3: mygrpcservice.ReadPropertyResponse
	(*UpdatePropertyRequest)(nil),  // 4: mygrpcservice.UpdatePropertyRequest
	(*UpdatePropertyResponse)(nil), // 5: mygrpcservice.UpdatePropertyResponse
	(*DeletePropertyRequest)(nil),  // 6: mygrpcservice.DeletePropertyRequest
	(*DeletePropertyResponse)(nil), // 7: mygrpcservice.DeletePropertyResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),   // 9: google.protobuf.BoolValue
}
var file_property_service_proto_depIdxs = []int32{
	8,  // 0: mygrpcservice.CreatePropertyRequest.available_date:type_name -> google.protobuf.Timestamp
	9,  // 1: mygrpcservice.ReadPropertyResponse.available:type_name -> google.protobuf.BoolValue
	8,  // 2: mygrpcservice.ReadPropertyResponse.available_date:type_name -> google.protobuf.Timestamp
	9,  // 3: mygrpcservice.UpdatePropertyRequest.available:type_name -> google.protobuf.BoolValue
	8,  // 4: mygrpcservice.UpdatePropertyRequest.available_date:type_name -> google.protobuf.Timestamp
	0,  // 5: mygrpcservice.PropertyService.Create:input_type -> mygrpcservice.CreatePropertyRequest
	2,  // 6: mygrpcservice.PropertyService.Read:input_type -> mygrpcservice.ReadPropertyRequest
	4,  // 7: mygrpcservice.PropertyService.Update:input_type -> mygrpcservice.UpdatePropertyRequest
	6,  // 8: mygrpcservice.PropertyService.Delete:input_type -> mygrpcservice.DeletePropertyRequest
	2,  // 9: mygrpcservice.PropertyService.ReadProperty:input_type -> mygrpcservice.ReadPropertyRequest
	0,  // 10: mygrpcservice.PropertyService.CreateProperty:input_type -> mygrpcservice.CreatePropertyRequest
	4,  // 11: mygrpcservice.PropertyService.UpdateProperty:input_type -> mygrpcservice.UpdatePropertyRequest
	6,  // 12: mygrpcservice.PropertyService.DeleteProperty:input_type -> mygrpcservice.DeletePropertyRequest
	1,  // 13: mygrpcservice.PropertyService.Create:output_type -> mygrpcservice.CreatePropertyResponse
	3,  // 14: mygrpcservice.PropertyService.Read:output_type -> mygrpcservice.ReadPropertyResponse
	5,  // 15: mygrpcservice.PropertyService.Update:output_type -> mygrpcservice.UpdatePropertyResponse
	7,  // 16: mygrpcservice.PropertyService.Delete:output_type -> mygrpcservice.DeletePropertyResponse
	3,  // 17: mygrpcservice.PropertyService.ReadProperty:output_type -> mygrpcservice.ReadPropertyResponse
	1,  // 18: mygrpcservice.PropertyService.CreateProperty:output_type -> mygrpcservice.CreatePropertyResponse
	5,  // 19: mygrpcservice.PropertyService.UpdateProperty:output_type -> mygrpcservice.UpdatePropertyResponse
	7,  // 20: mygrpcservice.PropertyService.DeleteProperty:output_type -> mygrpcservice.DeletePropertyResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_property_service_proto_init() }
func file_property_service_proto_init() {
	if File_property_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_property_service_proto_rawDesc), len(file_property_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_service_proto_goTypes,
		DependencyIndexes: file_property_service_proto_depIdxs,
		MessageInfos:      file_property_service_proto_msgTypes,
	}.Build()
	File_property_service_proto = out.File
	file_property_service_proto_goTypes = nil
	file_property_service_proto_depIdxs = nil
}
