// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: owner_service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request and Response messages for the Create operation.
type CreateOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Telephone     string                 `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerRequest) Reset() {
	*x = CreateOwnerRequest{}
	mi := &file_owner_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerRequest) ProtoMessage() {}

func (x *CreateOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerRequest.ProtoReflect.Descriptor instead.
func (*CreateOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOwnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOwnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOwnerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOwnerRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

type CreateOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerResponse) Reset() {
	*x = CreateOwnerResponse{}
	mi := &file_owner_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerResponse) ProtoMessage() {}

func (x *CreateOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerResponse.ProtoReflect.Descriptor instead.
func (*CreateOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOwnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request and Response messages for the Read operation.
type ReadOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOwnerRequest) Reset() {
	*x = ReadOwnerRequest{}
	mi := &file_owner_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOwnerRequest) ProtoMessage() {}

func (x *ReadOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOwnerRequest.ProtoReflect.Descriptor instead.
func (*ReadOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOwnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Telephone     string                 `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOwnerResponse) Reset() {
	*x = ReadOwnerResponse{}
	mi := &file_owner_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOwnerResponse) ProtoMessage() {}

func (x *ReadOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOwnerResponse.ProtoReflect.Descriptor instead.
func (*ReadOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadOwnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadOwnerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadOwnerResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReadOwnerResponse) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

// Request and Response messages for the Update operation.
type UpdateOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Telephone     string                 `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOwnerRequest) Reset() {
	*x = UpdateOwnerRequest{}
	mi := &file_owner_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOwnerRequest) ProtoMessage() {}

func (x *UpdateOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOwnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOwnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOwnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOwnerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateOwnerRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

type UpdateOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOwnerResponse) Reset() {
	*x = UpdateOwnerResponse{}
	mi := &file_owner_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOwnerResponse) ProtoMessage() {}

func (x *UpdateOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOwnerResponse.ProtoReflect.Descriptor instead.
func (*UpdateOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOwnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request and Response messages for the Delete operation.
type DeleteOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOwnerRequest) Reset() {
	*x = DeleteOwnerRequest{}
	mi := &file_owner_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOwnerRequest) ProtoMessage() {}

func (x *DeleteOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOwnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOwnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOwnerResponse) Reset() {
	*x = DeleteOwnerResponse{}
	mi := &file_owner_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOwnerResponse) ProtoMessage() {}

func (x *DeleteOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owner_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOwnerResponse.ProtoReflect.Descriptor instead.
func (*DeleteOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owner_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteOwnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_owner_service_proto protoreflect.FileDescriptor

const file_owner_service_proto_rawDesc = "" +
	"\n" +
	"\x13owner_service.proto\x12\rmygrpcservice\x1a\x1cgoogle/api/annotations.proto\"l\n" +
	"\x12CreateOwnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\ttelephone\x18\x04 \x01(\tR\ttelephone\"%\n" +
	"\x13CreateOwnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10ReadOwnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x11ReadOwnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\ttelephone\x18\x04 \x01(\tR\ttelephone\"l\n" +
	"\x12UpdateOwnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\ttelephone\x18\x04 \x01(\tR\ttelephone\"%\n" +
	"\x13UpdateOwnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteOwnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeleteOwnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xc1\x03\n" +
	"\fOwnerService\x12j\n" +
	"\vCreateOwner\x12!.mygrpcservice.CreateOwnerRequest\x1a\".mygrpcservice.CreateOwnerResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/owner\x12f\n" +
	"\tReadOwner\x12\x1f.mygrpcservice.ReadOwnerRequest\x1a .mygrpcservice.ReadOwnerResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/owner/{id}\x12o\n" +
	"\vUpdateOwner\x12!.mygrpcservice.UpdateOwnerRequest\x1a\".mygrpcservice.UpdateOwnerResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/owner/{id}\x12l\n" +
	"\vDeleteOwner\x12!.mygrpcservice.DeleteOwnerRequest\x1a\".mygrpcservice.DeleteOwnerResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/owner/{id}B\"Z property-service/api/proto;protob\x06proto3"

var (
	file_owner_service_proto_rawDescOnce sync.Once
	file_owner_service_proto_rawDescData []byte
)

func file_owner_service_proto_rawDescGZIP() []byte {
	file_owner_service_proto_rawDescOnce.Do(func() {
		file_owner_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_owner_service_proto_rawDesc), len(file_owner_service_proto_rawDesc)))
	})
	return file_owner_service_proto_rawDescData
}

var file_owner_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_owner_service_proto_goTypes = []any{
	(*CreateOwnerRequest)(nil),  // 0: mygrpcservice.CreateOwnerRequest
	(*CreateOwnerResponse)(nil), // 1: mygrpcservice.CreateOwnerResponse
	(*ReadOwnerRequest)(nil),    // 2: mygrpcservice.ReadOwnerRequest
	(*ReadOwnerResponse)(nil),   // 3: mygrpcservice.ReadOwnerResponse
	(*UpdateOwnerRequest)(nil),  // 4: mygrpcservice.UpdateOwnerRequest
	(*UpdateOwnerResponse)(nil), // 5: mygrpcservice.UpdateOwnerResponse
	(*DeleteOwnerRequest)(nil),  // 6: mygrpcservice.DeleteOwnerRequest
	(*DeleteOwnerResponse)(nil), // 7: mygrpcservice.DeleteOwnerResponse
}
var file_owner_service_proto_depIdxs = []int32{
	0, // 0: mygrpcservice.OwnerService.CreateOwner:input_type -> mygrpcservice.CreateOwnerRequest
	2, // 1: mygrpcservice.OwnerService.ReadOwner:input_type -> mygrpcservice.ReadOwnerRequest
	4, // 2: mygrpcservice.OwnerService.UpdateOwner:input_type -> mygrpcservice.UpdateOwnerRequest
	6, // 3: mygrpcservice.OwnerService.DeleteOwner:input_type -> mygrpcservice.DeleteOwnerRequest
	1, // 4: mygrpcservice.OwnerService.CreateOwner:output_type -> mygrpcservice.CreateOwnerResponse
	3, // 5: mygrpcservice.OwnerService.ReadOwner:output_type -> mygrpcservice.ReadOwnerResponse
	5, // 6: mygrpcservice.OwnerService.UpdateOwner:output_type -> mygrpcservice.UpdateOwnerResponse
	7, // 7: mygrpcservice.OwnerService.DeleteOwner:output_type -> mygrpcservice.DeleteOwnerResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_owner_service_proto_init() }
func file_owner_service_proto_init() {
	if File_owner_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_owner_service_proto_rawDesc), len(file_owner_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_owner_service_proto_goTypes,
		DependencyIndexes: file_owner_service_proto_depIdxs,
		MessageInfos:      file_owner_service_proto_msgTypes,
	}.Build()
	File_owner_service_proto = out.File
	file_owner_service_proto_goTypes = nil
	file_owner_service_proto_depIdxs = nil
}
